### PR TITLE
validate minter role before set a supply total

### PR DESCRIPTION
**Pull request by suraneti**

### CODE REVIEW

**Comment by suraneti** [comment]
@jowenshaw Thanks for your response and explanation, I think it has possibilities for an invalid `minter`  address input that executes by a human (aka `DEFAULT_ADMIN_ROLE`), so if it happens this invalid `minter` address is stored in `minterSupply` forever. 

This might not be affected the functional core but some Dapp might get the data from this contract to display the statistics.

**Comment by jowenshaw** [comment]
when the admin call `setMinterTotal` with wrong parameters, the admin can call again `setMinterTotal` to correct it (clear or adjust) even after the minter is removed.

**Comment by suraneti** [comment]
@jowenshaw I understand but this just adjusts the total to `0`, but doesn't prevent storing an invalid `minter` address in `minterSupply` mapping.

**Comment by jowenshaw** [comment]
@suraneti thanks for your advice.
I'd like do it like this way, add a `force` flag.
when the flag is `false`, the minter role will be checked as normally.
when the flag is `true`, the admin will think once again of his operation.

```
function setMinterTotal(address minter, uint256 total, bool force) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(force || hasRole(MINTER_ROLE, minter), "not minter");
        minterSupply[minter].total = total;
}
```

**Pull request closed without merging**
